version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_DATABASE: bitnami_moodle
      MYSQL_USER: bn_moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - mariadb_data:/var/lib/mysql

  moodle:
    image: bitnami/moodle:4
    container_name: moodle
    depends_on:
      - mariadb
    restart: always
    ports:
      - "8080:8080"   # Moodle Web UI
      - "8443:8443"   # SSL (optional)
    environment:
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: bn_moodle
      MOODLE_DATABASE_NAME: bitnami_moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin123
    volumes:
      - moodle_data:/bitnami/moodle
      - moodle_data_data:/bitnami/moodledata
      - ./themes/manfree:/bitnami/moodle/theme/manfree

  jobe:
    image: trampgeek/jobeinabox
    container_name: jobe
    restart: always
    ports:
      - "4000:80"

volumes:
  mariadb_data:
  moodle_data:
  moodle_data_data:
