version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - mariadb_data:/var/lib/mysql

  moodle:
    image: moodle:4.1-apache
    container_name: moodle
    depends_on:
      - mariadb
    restart: always
    ports:
      - "8080:80"
    environment:
      MOODLE_DB_HOST: mariadb
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASSWORD: moodle
    volumes:
      - moodle_data:/var/www/html
      - moodle_data_data:/var/www/moodledata
      - ./themes/manfree:/var/www/html/theme/manfree

  jobe:
    image: trampgeek/jobeinabox
    container_name: jobe
    restart: always
    ports:
      - "4000:80"

volumes:
  mariadb_data:
  moodle_data:
  moodle_data_data: